// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NoWait.Data;

#nullable disable

namespace NoWait.Migrations
{
    [DbContext(typeof(NoWaitContext))]
    partial class NoWaitContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NoWait.Models.Ingredient", b =>
                {
                    b.Property<int>("IngredientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngredientID"));

                    b.Property<int?>("MenuItemID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IngredientID");

                    b.HasIndex("MenuItemID");

                    b.ToTable("Ingredient", (string)null);
                });

            modelBuilder.Entity("NoWait.Models.MenuItem", b =>
                {
                    b.Property<int>("MenuItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuItemID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("foodCategory")
                        .HasColumnType("int");

                    b.HasKey("MenuItemID");

                    b.ToTable("MenuItem", (string)null);
                });

            modelBuilder.Entity("NoWait.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("ItemMenuItemID")
                        .HasColumnType("int");

                    b.Property<int?>("ReservationId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("ItemMenuItemID");

                    b.HasIndex("ReservationId");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("NoWait.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationId"));

                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.HasKey("ReservationId");

                    b.HasIndex("TableId");

                    b.ToTable("Reservation", (string)null);
                });

            modelBuilder.Entity("NoWait.Models.Table", b =>
                {
                    b.Property<int>("TableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TableId"));

                    b.Property<int>("chairCount")
                        .HasColumnType("int");

                    b.HasKey("TableId");

                    b.ToTable("Table", (string)null);
                });

            modelBuilder.Entity("NoWait.Models.Ingredient", b =>
                {
                    b.HasOne("NoWait.Models.MenuItem", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("MenuItemID");
                });

            modelBuilder.Entity("NoWait.Models.Order", b =>
                {
                    b.HasOne("NoWait.Models.MenuItem", "Item")
                        .WithMany()
                        .HasForeignKey("ItemMenuItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NoWait.Models.Reservation", null)
                        .WithMany("Orders")
                        .HasForeignKey("ReservationId");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("NoWait.Models.Reservation", b =>
                {
                    b.HasOne("NoWait.Models.Table", "Table")
                        .WithMany()
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Table");
                });

            modelBuilder.Entity("NoWait.Models.MenuItem", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("NoWait.Models.Reservation", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
